version: .{build}
clone_folder: c:\work\sharp-arch

pull_requests:
  do_not_increment_build_number: true

nuget:
  disable_publish_on_pr: true

image:
  - Visual Studio 2019

services:
  - mssql2017


environment:
  coveralls_repo_token:
    secure: FgZlD1O2ilcGB6nF7cIgNcF6f8wWJk//ish6EG800QfuMd0y3BQWUXkl9u7TB4yG
  appveyor_cache_entry_zip_args: -t7z -m0=lzma -mx=5 -ms=on
  CAKE_PATHS_TOOLS: c:\tmp\cake\tools\
  CAKE_SETTINGS_SKIPVERIFICATION: true
  CAKE_SETTINGS_SKIPPACKAGEVERSIONCHECK: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  GITHUB_TOKEN:
    secure: FgP/dEF7lumDgbjt3tzPSDqDTM16uoiPfKZPQSLJO+/GaIR2zSquSh0pXP8znx+c

cache:
#  - c:\work\sharp-arch\tmp\ResharperCaches
#  - c:\work\sharp-arch\tmp\DupFinderCaches
  - c:\tmp\cake\tools -> appveyor.yml

install:
  - ps: ./mssql-setup.ps1
  - ps: ./dotnet-install.ps1 -Version 6.0.100-preview.7.21379.14 -InstallDir "C:\Program Files\dotnet"
  - ps: dotnet new tool-manifest
  - ps: dotnet tool install Cake.Tool --version 1.2.0

build_script:
  - ps: dotnet cake

test: off

artifacts:
  - path: Drops/Packages/*.nupkg
    name: NuGet packages

  - path: Drops/Packages/*.snupkg
    name: NuGet symbol packages
    type: NuGetPackage
#  - path: Drops/Inspections/CodeDuplicates.html
#    name: CodeDuplicates
#  - path: Drops/Inspections/CodeInspections.html
#    name: CodeInspections

deploy:
  - provider: NuGet
    name: Pre-release
    api_key:
      secure: kvGBJqOLM4uyxv3IVpAC9ZjMSPaL0bnvAXJeK0t1TbL3wpBa7raxKLETd4px1/LY
    on:
      branch:
        - develop
        - /release\/v.*/
        - /releases.*/
        - /hotfixes.*/

  - provider: NuGet
    name: Tagged release
    api_key:
      secure: kvGBJqOLM4uyxv3IVpAC9ZjMSPaL0bnvAXJeK0t1TbL3wpBa7raxKLETd4px1/LY
    on:
      appveyor_repo_tag: true
