version: 3.1.{build}
clone_depth: 3
clone_folder: c:\work\sharp-arch
install:
- cmd: git submodule update --init --recursive
build:
  project: Build\build.proj
  parallel: true
  verbosity: normal
test_script:
- cmd: >-
    cd Solutions\SharpArch.Tests\bin\Release

    nunit3-console SharpArch.Tests.dll --result=myresults.xml;format=AppVeyor --dispose-runners --nocolor

    cd ..\..\..\SharpArch.Specifications\bin\Release

    mspec-clr4.exe SharpArch.Specifications.dll